new usb-acm-mtp-setup script with start/stop may work as service unmodified i dont need that yet so havent tested

diff --git a/tools/16ton/mtp_adb/usb-acm-mtp-setup b/tools/16ton/mtp_adb/usb-acm-mtp-setup
--- a/tools/16ton/mtp_adb/usb-acm-mtp-setup
+++ b/tools/16ton/mtp_adb/usb-acm-mtp-setup
@@ -1,5 +1,9 @@
 #!/bin/bash
 # mount -o bind /sdcard /root/sdcard
+
+
+case "$1" in
+    start)
 modprobe usb_f_fs
 modprobe usb_f_mtp
 modprobe usb_f_ptp
@@ -35,7 +39,7 @@ ln -s functions/acm.GS0 configs/c.1
 mkdir /sys/kernel/config/usb_gadget/g1/functions/mtp.mtp
 ln -s /sys/kernel/config/usb_gadget/g1/functions/mtp.mtp /sys/kernel/config/usb_gadget/g1/configs/c.1/mtp.mtp
 mkdir /dev/mtp
-# mount -t functionfs mtp /dev/mtp
+# mount mtp -t functionfs /dev/mtp
 
 echo "Creating Mass Storage interface"
 mkdir functions/mass_storage.ms0
@@ -43,8 +47,47 @@ echo "/dev/mmcblk0" > functions/mass_storage.ms0/lun.0/file
 echo "1" > functions/mass_storage.ms0/lun.0/removable
 ln -s functions/mass_storage.ms0 configs/c.1/mass_storage.ms0
 
-#Enable the Gadget      echo `ls /sys/class/udc` > UDC
+#Enable the Gadget
 #Replace "ci_hdrc.0" with your platform UDC driver as found in /sys/class/udc/
-echo `ls /sys/class/udc` > /sys/kernel/config/usb_gadget/g1/UDC
+#export udcX=$(ls /sys/class/udc/)
+#echo $udcX
+echo $(ls /sys/class/udc/) > /sys/kernel/config/usb_gadget/g1/UDC
 mtp-server &
 getty ttyGS0 115200 linux &
+;;
+    stop)
+killall mtp-server
+killall getty
+cd /sys/kernel/config/usb_gadget/g1
+if [ $? -ne 0 ]; then
+	echo "Error: no configfs gadget found"
+	exit 1;
+fi
+echo "Unbinding USB Device Controller"
+	echo "" > UDC
+
+echo "Removing MTP interface"
+rm configs/c.1/mtp.mtp
+rmdir functions/mtp.mtp
+
+echo "Removing ACM interface"
+rm configs/c.1/acm.GS0
+rmdir functions/acm.GS0
+
+echo "Removing mass_storage interface"
+rm configs/c.1/mass_storage.ms0
+rmdir functions/mass_storage.ms0
+
+echo "Clearing English strings"
+rmdir strings/0x409
+
+echo "Cleaning up configuration"
+rmdir configs/c.1/strings/0x409
+rmdir configs/c.1
+
+echo "Removing gadget directory"
+cd /sys/kernel/config/usb_gadget
+rmdir g1
+;;
+esac
+
